```{r packages}

library(tidyverse)
library(gganimate)
library(transformr)
library(scales)
library(usmap)
library(lubridate)
library(gifski)
library(png)
library(DescTools)

url <- "https://raw.githubusercontent.com/alex/nyt-2020-election-scraper/master/all-state-changes.csv"

votes <- read_csv(url) %>% 
  mutate(state = str_replace(state, " \\(.*\\)", ""),
         state = state.abb[match(state, state.name)],
         timestamp = ymd_hms(timestamp),
         pct_reported = precincts_reporting / precincts_total * 100)

```

```{r sim_data}

simulations <- read_csv("data/election_simulation_results.csv")

set.seed(9)
ev_uncertainty <- simulations %>% 
  mutate(biden_win = ifelse(sim_dvotes_2020 > sim_rvotes_2020, 1, 0)) %>% 
  group_by(state, electoral_votes) %>% 
  summarise(pct_biden_win = mean(biden_win, na.rm = TRUE)) %>% 
  mutate(close = pct_biden_win - .5) %>% 
  arrange(abs(close)) %>% 
  select(state, pct_biden_win, electoral_votes) %>% 
  
  # simulating 100,000 elections in each state with the given win probabilities
  
  slice(rep(1:n(), each = 100000)) %>% 
  mutate(biden_win = map_int(pct_biden_win, ~ rbinom(1, 1, .)),
         id = 1:100000,
         biden_ev = ifelse(biden_win == 1, electoral_votes, 0),
         trump_ev = ifelse(biden_win == 0, electoral_votes, 0))


```

```{r biden_wins}

# getting list of states that Biden won in each simulation

ev_sim_results <- ev_uncertainty %>% 
  group_by(id) %>% 
  mutate(biden_win = as.character(biden_win),
    biden_win = case_when(biden_win == "1" ~ state)) %>% 
  drop_na(biden_win) %>% 
  select(id, biden_win) %>% 
  nest() %>% 
  arrange(id)

# comparing to the states that Biden actually won

biden_actual_results <- c("WA", "OR", "CA", "AZ", "NM", "CO", "MN", "WI", "IL", "MI", "VA",
                          "MD", "DE", "NJ", "CT", "RI", "MA", "NH", "VT", "ME")

```


```{r timeline}


votes %>% 
  filter(state == "GA") %>% 
  mutate(trump_votes = case_when(leading_candidate_name == "Trump" ~ leading_candidate_votes,
                                 TRUE ~ trailing_candidate_votes),
         biden_votes = case_when(leading_candidate_name == "Biden" ~ leading_candidate_votes,
                                 TRUE ~ trailing_candidate_votes),
         trump_pv2p = trump_votes / (biden_votes + trump_votes),
         biden_pv2p = biden_votes / (biden_votes + trump_votes)) %>% 
  pivot_longer(cols = trump_pv2p:biden_pv2p, names_to = "candidate", values_to = "pv2p") %>% 
  ggplot(aes(timestamp, pv2p, color = candidate)) +
  geom_line()

```

```{r anim_map}

us_map <- map_data("state") %>% 
  mutate(region = toupper(region),
    region = state.abb[match(region,  toupper(state.name))])

p <- votes %>%  
  mutate(trump_votes = case_when(leading_candidate_name == "Trump" ~ leading_candidate_votes,
                                 TRUE ~ trailing_candidate_votes),
         biden_votes = case_when(leading_candidate_name == "Biden" ~ leading_candidate_votes,
                                 TRUE ~ trailing_candidate_votes),
         trump_pv2p = trump_votes / (biden_votes + trump_votes),
         biden_pv2p = biden_votes / (biden_votes + trump_votes),
         biden_margin = biden_pv2p - trump_pv2p) %>% 
  left_join(us_map, by = c("state" = "region")) %>% 
  mutate(date = ymd(str_sub(timestamp, end = 10)),
    time = hms(str_sub(timestamp, 11)),
    hour = str_sub(time, end = 2),
    pct_reported = RoundTo(pct_reported, 10)) %>% 
  group_by(state, pct_reported, long, lat) %>% 
  mutate(biden_margin = mean(biden_margin)) %>% 
  ungroup() %>% 
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = biden_margin), 
                color = "white") +
  coord_sf() +
  theme_void() +
  scale_fill_gradientn(colours = c(my_red, "white", muted("blue")),
                       breaks = c(-0.4, 0, 0.4)) +
  labs(title = "",
       fill = "Democratic Vote Margin (%)") +
  theme_hodp() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) 
p + 
  transition_manual(pct_reported)

```


